#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

NAME="computer-vision-01"

az group create --name "${NAME}" --location "East US"
az group deployment create \
  --name "${NAME}" \
  --resource-group "${NAME}" \
  --template-file "${DIR}/../arm-templates/template.json" \
  --parameters @"${DIR}/../arm-templates/parameters.json"
